### ISSUE TITLE
DATABASE_USERS_AND_PASSWORDS not used on some places in tests

### ISSUE THREAD

**Issue by bbozo** [rsim/ruby-plsql#42]
Which means if you can't use default user names a lot of tests will break

**Comment by jgebal** [comment]
I suppose it would be more convenient to use ruby-plsql-spec, as it adds a `database.yml` configuration on top of ruby-plsql, so you can easily use any connections you want.

**Comment by javornikolov** [comment]
Indeed, now 'hr' schema name is hard-coded in multiple places in the tests. Allowing to overriding the schema name would make a few tests (we have about 10 like these) a bit more obscure. E.g. instead of
``` ruby
plsql.hr.schema_name
```
we'll need something like
``` ruby
eval "plsql.#{DB_USERS[0]}.schema_name"
# or
plsql.send(DB_USERS[0]).schema_name
```

Yet, README may be referenced for cleaner examples so maybe it's not a huge trouble to switch to dynamic calls for these few specs.

**Comment by bbozo** [comment]
Or just globally include a helper? :) So it's clear what you meant in the tests?

``` ruby
def schema_name
  plsql.send(DB_USERS[0]).schema_name
end
```

**Comment by javornikolov** [comment]
It might be handy to have such helper for some of the cases. But the min point in some of these tests is to examine that plsql.hr is properly resolved to the relevant schema object; and another level of indirection may make that less obvious.
